student_count = 11

puts "The students of Villains Academy"
puts "----------------"
puts "Dir. Hannibal Lecter"
puts"Dark Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "The Wickde Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
puts "Overall, we have #{student_count} great students"